name: Release Test
on:   
  workflow_dispatch:
  
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
      - name: Set current date as env variable
        run: echo "DATE::$(date +'%Y-%m-%d'date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo curresnt date
        run: echo $DATE
    
    
    - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}
    
    
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1500
          swap-size-mb: 1024
          remove-dotnet: 'true'
    
      - name: Check free disk space in current folder
        run:  df -h .

      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove user interaction in script
        run:  sed -i '63,86d' ctbankix_lubuntu_20.04.3.sh
        
      - name: Add execution bit in file mode
        run:  chmod +x ctbankix_lubuntu_20.04.3.sh
        
      - name: Execute script
        run:  sudo ./ctbankix_lubuntu_20.04.3.sh
        
      - name: Check free disk space in current folder
        run:  df -h .
