name: Release Test
on:   
  workflow_dispatch:
  
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo ${{env.DATE}}
