name: Build for test
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
  
  schedule:
  - cron: '0 1 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Check free disk space in current folder
        run:  df -h .

      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove user interaction in script
        run:  sed -i '63,86d' ctbankix_lubuntu_20.04.3.sh
        
      - name: Add execution bit in file mode
        run:  chmod +x ctbankix_lubuntu_20.04.3.sh
        
      - name: Execute script
        run:  sudo ./ctbankix_lubuntu_20.04.3.sh
        
      - name: Check free disk space in current folder
        run:  df -h .
